# Generated by Django 5.2.7 on 2026-03-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Condiciones',
            field=models.TextField(blank=True),
        ),
    ]
