# Generated by Django 6.0.4 on 2026-04-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_producto_imagen_alter_restaurante_logo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('restaurante', 'nombre'), name='unique_categoria_por_restaurante'),
        ),
    ]
