# Generated by Django 6.0.4 on 2026-04-12 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_categoria_unique_categoria_por_restaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Condiciones',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='menu.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='menu.restaurante'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('restaurante', 'nombre'), name='unique_producto_por_restaurante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='condiciones',
            field=models.TextField(blank=True),
        ),
    ]
