# Generated by Django 6.0.4 on 2026-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_producto_condiciones_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('restaurante', 'categoria', 'orden'), name='unique_orden_por_categoria'),
        ),
    ]
