# Generated by Django 6.0.4 on 2026-04-25 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_producto_unique_orden_por_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(blank=True, null=True)),
                ('producto_nombre', models.CharField(max_length=150)),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('EDITADO', 'Editado'), ('ELIMINADO', 'Eliminado'), ('DISPONIBLE', 'Cambio de disponibilidad'), ('PRECIO', 'Cambio de precio'), ('ORDEN', 'Cambio de orden')], max_length=20)),
                ('descripcion', models.TextField()),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
