# Generated by Django 6.0.4 on 2026-04-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_bitacoraproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('mesa_asignada', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion_admin', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to='menu.usuariorestaurante')),
                ('gestionada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_gestionadas', to='menu.usuariorestaurante')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='menu.restaurante')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
