# Generated by Django 6.0.4 on 2026-04-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_restaurante_sitio_web_alter_restaurante_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
