# Generated by Django 6.0.4 on 2026-04-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_restaurante_descripcion_alter_restaurante_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorestaurante',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to='menu.usuariorestaurante'),
        ),
    ]
